<?php

namespace AppBundle\Repository;

/**
 * biddingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class biddingRepository extends \Doctrine\ORM\EntityRepository
{
    public function maxBid($id)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = '
        SELECT * FROM bidding 
        WHERE product_id = :id
        ORDER BY bid DESC
        LIMIT 1  
        ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['id'=>$id]);

        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }

    public function findBid($user_id)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = '
        SELECT * FROM bidding 
        WHERE user_id = :user_id
        ORDER BY bid DESC
        ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['user_id'=>$user_id]);

        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }
}
